apiVersion: apps/v1
kind: Deployment
metadata:
  name: flood-risk-stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: flood-risk
  template:
    metadata:
      labels:
        app: flood-risk
    spec:
      containers:
        - name: api
          image: flood-risk-ml:v1
          ports:
            - containerPort: 8000
